# -*- coding: utf-8 -*-
"""assino1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwKfkhAvEn4iRyXkBK_ZSfwITNb3pGFd
"""

# ============================================================
# ML CLOUD OPTIMISATION LAB — OUTCOME 3
# Unsupervised Clustering & Dimensionality Reduction
# Student: C026-01-0736/2020
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json
import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from scipy.cluster.hierarchy import dendrogram, linkage

warnings.filterwarnings('ignore')

# ── Student Information ──
STUDENT_REG_NO = "C026-01-0736/2020"
STUDENT_NAME = "Irungu faith wamuyu"

# ── Setup ──
SEED = 42
np.random.seed(SEED)
os.makedirs('figures', exist_ok=True)
os.makedirs('results', exist_ok=True)

print("=" * 60)
print("ML CLOUD OPTIMISATION LAB — OUTCOME 3")
print(f"Student: {STUDENT_REG_NO}")
print("Unsupervised Clustering & Dimensionality Reduction")
print("=" * 60)

# ============================================================
# 1. LOAD & PREPARE DATA
# ============================================================

print("\n📊 Loading Cloud Telemetry Dataset...")

# ── Generate synthetic cloud data for clustering ──
def generate_clustering_data(n_samples=5000, seed=42):
    """Generate synthetic cloud workload data."""
    np.random.seed(seed)

    # Create 4 distinct workload patterns
    data = []
    labels = []

    # Pattern 1: CPU-intensive workloads
    n1 = int(n_samples * 0.3)
    data.append(np.random.multivariate_normal(
        [80, 30, 200, 150, 50],
        [[10, 2, 5, 3, 2], [2, 8, 3, 2, 1], [5, 3, 20, 5, 3], [3, 2, 5, 15, 2], [2, 1, 3, 2, 8]],
        n1
    ))
    labels.extend([0] * n1)

    # Pattern 2: Memory-intensive workloads
    n2 = int(n_samples * 0.25)
    data.append(np.random.multivariate_normal(
        [30, 85, 300, 100, 80],
        [[8, 3, 5, 2, 3], [3, 10, 4, 3, 5], [5, 4, 25, 5, 4], [2, 3, 5, 12, 3], [3, 5, 4, 3, 10]],
        n2
    ))
    labels.extend([1] * n2)

    # Pattern 3: Network-intensive workloads
    n3 = int(n_samples * 0.25)
    data.append(np.random.multivariate_normal(
        [40, 40, 500, 200, 60],
        [[8, 3, 5, 4, 2], [3, 8, 4, 3, 2], [5, 4, 30, 8, 5], [4, 3, 8, 20, 3], [2, 2, 5, 3, 8]],
        n3
    ))
    labels.extend([2] * n3)

    # Pattern 4: Balanced/mixed workloads
    n4 = n_samples - n1 - n2 - n3
    data.append(np.random.multivariate_normal(
        [50, 50, 350, 150, 70],
        [[10, 4, 6, 4, 3], [4, 10, 5, 4, 4], [6, 5, 25, 6, 5], [4, 4, 6, 15, 4], [3, 4, 5, 4, 10]],
        n4
    ))
    labels.extend([3] * n4)

    data = np.vstack(data)

    # Create DataFrame
    df = pd.DataFrame(data, columns=[
        'cpu_usage', 'memory_usage', 'network_bandwidth',
        'disk_io', 'request_rate'
    ])

    # Add some realistic noise
    df += np.random.normal(0, 2, df.shape)
    df = df.clip(lower=0)

    # Add categorical features
    df['task_type'] = np.random.choice(['batch', 'streaming', 'interactive', 'background'], n_samples)
    df['priority'] = np.random.choice(['high', 'medium', 'low'], n_samples)

    return df, labels

# ── Generate data ──
df, true_labels = generate_clustering_data(n_samples=5000)
print(f"✅ Dataset generated: {df.shape[0]:,} rows, {df.shape[1]} columns")

# ── Display data info ──
print("\n📋 Data Info:")
print(df.info())

print("\n📊 First 5 rows:")
print(df.head())

# ============================================================
# 2. DATA PREPROCESSING
# ============================================================

print("\n" + "=" * 60)
print("🔧 DATA PREPROCESSING")
print("=" * 60)

# ── Select numeric features for clustering ──
numeric_cols = ['cpu_usage', 'memory_usage', 'network_bandwidth', 'disk_io', 'request_rate']
X = df[numeric_cols].copy()

print(f"✅ Selected {len(numeric_cols)} features for clustering:")
for col in numeric_cols:
    print(f"   - {col}")

# ── Standardize the data ──
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled_df = pd.DataFrame(X_scaled, columns=numeric_cols)

print("\n✅ Data standardized (mean=0, std=1)")

# ── Save processed data ──
X_scaled_df.to_csv('results/clustering_data_scaled.csv', index=False)
print("✅ Scaled data saved to: results/clustering_data_scaled.csv")

# ============================================================
# 3. ELBOW METHOD & SILHOUETTE SWEEP (Optimal K)
# ============================================================

print("\n" + "=" * 60)
print("📊 DETERMINING OPTIMAL K")
print("=" * 60)

# ── Test different K values ──
k_range = range(2, 11)
inertias = []
silhouette_scores = []
davies_bouldin_scores = []
calinski_harabasz_scores = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=SEED, n_init=10)
    labels = kmeans.fit_predict(X_scaled)

    inertias.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(X_scaled, labels))
    davies_bouldin_scores.append(davies_bouldin_score(X_scaled, labels))
    calinski_harabasz_scores.append(calinski_harabasz_score(X_scaled, labels))

# ── Plot Elbow Method ──
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Elbow plot
axes[0, 0].plot(k_range, inertias, 'bo-', linewidth=2, markersize=8)
axes[0, 0].axvline(x=4, color='red', linestyle='--', label='Optimal K=4')
axes[0, 0].set_xlabel('Number of Clusters (K)')
axes[0, 0].set_ylabel('Inertia (Within-cluster sum of squares)')
axes[0, 0].set_title('Elbow Method for Optimal K', fontweight='bold')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# Silhouette Score
axes[0, 1].plot(k_range, silhouette_scores, 'ro-', linewidth=2, markersize=8)
axes[0, 1].axvline(x=4, color='red', linestyle='--', label='Optimal K=4')
axes[0, 1].set_xlabel('Number of Clusters (K)')
axes[0, 1].set_ylabel('Silhouette Score')
axes[0, 1].set_title('Silhouette Score by K', fontweight='bold')
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

# Davies-Bouldin Index
axes[1, 0].plot(k_range, davies_bouldin_scores, 'go-', linewidth=2, markersize=8)
axes[1, 0].axvline(x=4, color='red', linestyle='--', label='Optimal K=4')
axes[1, 0].set_xlabel('Number of Clusters (K)')
axes[1, 0].set_ylabel('Davies-Bouldin Index (lower is better)')
axes[1, 0].set_title('Davies-Bouldin Index by K', fontweight='bold')
axes[1, 0].legend()
axes[1, 0].grid(True, alpha=0.3)

# Calinski-Harabasz Score
axes[1, 1].plot(k_range, calinski_harabasz_scores, 'mo-', linewidth=2, markersize=8)
axes[1, 1].axvline(x=4, color='red', linestyle='--', label='Optimal K=4')
axes[1, 1].set_xlabel('Number of Clusters (K)')
axes[1, 1].set_ylabel('Calinski-Harabasz Score (higher is better)')
axes[1, 1].set_title('Calinski-Harabasz Score by K', fontweight='bold')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.suptitle('Figure 1: Optimal K Selection Methods', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('figures/optimal_k_selection.png', dpi=300, bbox_inches='tight')
plt.close()
print("✅ Figure saved: figures/optimal_k_selection.png")

# ── Determine optimal K ──
optimal_k = 4  # Based on visualization
print(f"\n🎯 Optimal K determined: {optimal_k} (based on elbow and silhouette scores)")

# ============================================================
# 4. CLUSTERING ALGORITHMS
# ============================================================

print("\n" + "=" * 60)
print("🔍 APPLYING CLUSTERING ALGORITHMS")
print("=" * 60)

clustering_results = {}

# ── 4a: K-Means Clustering ──
print("\n" + "-" * 40)
print("K-MEANS CLUSTERING")
print("-" * 40)

kmeans = KMeans(n_clusters=optimal_k, random_state=SEED, n_init=10)
kmeans_labels = kmeans.fit_predict(X_scaled)

# Compute metrics
kmeans_silhouette = silhouette_score(X_scaled, kmeans_labels)
kmeans_db = davies_bouldin_score(X_scaled, kmeans_labels)
kmeans_ch = calinski_harabasz_score(X_scaled, kmeans_labels)

print(f"Silhouette Score: {kmeans_silhouette:.4f}")
print(f"Davies-Bouldin Index: {kmeans_db:.4f}")
print(f"Calinski-Harabasz Score: {kmeans_ch:.2f}")

clustering_results['K-Means'] = {
    'labels': kmeans_labels,
    'centers': kmeans.cluster_centers_,
    'silhouette': kmeans_silhouette,
    'davies_bouldin': kmeans_db,
    'calinski_harabasz': kmeans_ch
}

# ── 4b: Agglomerative Clustering ──
print("\n" + "-" * 40)
print("AGGLOMERATIVE CLUSTERING")
print("-" * 40)

agg = AgglomerativeClustering(n_clusters=optimal_k)
agg_labels = agg.fit_predict(X_scaled)

# Compute metrics
agg_silhouette = silhouette_score(X_scaled, agg_labels)
agg_db = davies_bouldin_score(X_scaled, agg_labels)
agg_ch = calinski_harabasz_score(X_scaled, agg_labels)

print(f"Silhouette Score: {agg_silhouette:.4f}")
print(f"Davies-Bouldin Index: {agg_db:.4f}")
print(f"Calinski-Harabasz Score: {agg_ch:.2f}")

clustering_results['Agglomerative'] = {
    'labels': agg_labels,
    'silhouette': agg_silhouette,
    'davies_bouldin': agg_db,
    'calinski_harabasz': agg_ch
}

# ── 4c: DBSCAN (Bonus) ──
print("\n" + "-" * 40)
print("DBSCAN CLUSTERING")
print("-" * 40)

# Try different eps values
eps_values = [0.3, 0.5, 0.7, 1.0]
best_eps = 0.5
best_dbscan_silhouette = -1

for eps in eps_values:
    dbscan = DBSCAN(eps=eps, min_samples=5)
    dbscan_labels = dbscan.fit_predict(X_scaled)

    n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
    n_noise = sum(dbscan_labels == -1)

    if n_clusters >= 2:
        try:
            score = silhouette_score(X_scaled[dbscan_labels != -1],
                                     dbscan_labels[dbscan_labels != -1])
            print(f"  eps={eps}: {n_clusters} clusters, {n_noise} noise points, Silhouette={score:.4f}")
            if score > best_dbscan_silhouette:
                best_dbscan_silhouette = score
                best_eps = eps
                best_dbscan_labels = dbscan_labels
        except:
            pass

# Use best DBSCAN parameters
dbscan = DBSCAN(eps=best_eps, min_samples=5)
dbscan_labels = dbscan.fit_predict(X_scaled)

n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_noise = sum(dbscan_labels == -1)

if n_clusters >= 2:
    # Compute metrics (excluding noise points)
    mask = dbscan_labels != -1
    dbscan_silhouette = silhouette_score(X_scaled[mask], dbscan_labels[mask])
    dbscan_db = davies_bouldin_score(X_scaled[mask], dbscan_labels[mask])
    dbscan_ch = calinski_harabasz_score(X_scaled[mask], dbscan_labels[mask])

    print(f"\nBest DBSCAN: eps={best_eps}, {n_clusters} clusters, {n_noise} noise points")
    print(f"Silhouette Score: {dbscan_silhouette:.4f}")
    print(f"Davies-Bouldin Index: {dbscan_db:.4f}")
    print(f"Calinski-Harabasz Score: {dbscan_ch:.2f}")

    clustering_results['DBSCAN'] = {
        'labels': dbscan_labels,
        'silhouette': dbscan_silhouette,
        'davies_bouldin': dbscan_db,
        'calinski_harabasz': dbscan_ch,
        'n_clusters': n_clusters,
        'n_noise': n_noise
    }
else:
    print(f"⚠️ DBSCAN found only {n_clusters} clusters. Skipping DBSCAN.")

# ============================================================
# 5. DIMENSIONALITY REDUCTION - PCA
# ============================================================

print("\n" + "=" * 60)
print("📉 DIMENSIONALITY REDUCTION - PCA")
print("=" * 60)

# ── Apply PCA ──
pca = PCA(n_components=2, random_state=SEED)
X_pca = pca.fit_transform(X_scaled)

print(f"✅ PCA applied: {X_scaled.shape[1]} features → 2 components")
print(f"   Explained variance ratio: {pca.explained_variance_ratio_}")
print(f"   Total variance explained: {sum(pca.explained_variance_ratio_)*100:.2f}%")

# ── Visualize PCA results ──
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# Plot 1: K-Means PCA
scatter1 = axes[0, 0].scatter(X_pca[:, 0], X_pca[:, 1],
                              c=kmeans_labels, cmap='viridis',
                              alpha=0.6, s=20)
axes[0, 0].scatter(pca.transform(kmeans.cluster_centers_)[:, 0],
                   pca.transform(kmeans.cluster_centers_)[:, 1],
                   c='red', marker='X', s=200, edgecolors='black',
                   linewidths=2, label='Centroids')
axes[0, 0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
axes[0, 0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
axes[0, 0].set_title('K-Means Clusters (PCA Projection)', fontweight='bold')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)
plt.colorbar(scatter1, ax=axes[0, 0])

# Plot 2: Agglomerative PCA
scatter2 = axes[0, 1].scatter(X_pca[:, 0], X_pca[:, 1],
                              c=agg_labels, cmap='plasma',
                              alpha=0.6, s=20)
axes[0, 1].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
axes[0, 1].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
axes[0, 1].set_title('Agglomerative Clusters (PCA Projection)', fontweight='bold')
axes[0, 1].grid(True, alpha=0.3)
plt.colorbar(scatter2, ax=axes[0, 1])

# Plot 3: DBSCAN PCA
if 'DBSCAN' in clustering_results:
    scatter3 = axes[1, 0].scatter(X_pca[:, 0], X_pca[:, 1],
                                  c=dbscan_labels, cmap='tab10',
                                  alpha=0.6, s=20)
    axes[1, 0].set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
    axes[1, 0].set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
    axes[1, 0].set_title(f'DBSCAN Clusters (PCA Projection) - eps={best_eps}', fontweight='bold')
    axes[1, 0].grid(True, alpha=0.3)
    plt.colorbar(scatter3, ax=axes[1, 0])

# Plot 4: Loadings / Feature Contributions
loadings = pca.components_.T
feature_names = numeric_cols

axes[1, 1].axhline(0, color='gray', linestyle='-', alpha=0.5)
axes[1, 1].axvline(0, color='gray', linestyle='-', alpha=0.5)

for i, (feature, load) in enumerate(zip(feature_names, loadings)):
    axes[1, 1].arrow(0, 0, load[0], load[1], head_width=0.02, head_length=0.03,
                     fc='red', ec='red', alpha=0.7)
    axes[1, 1].text(load[0]*1.2, load[1]*1.2, feature, fontsize=10, fontweight='bold')

axes[1, 1].set_xlabel('PC1 Loading')
axes[1, 1].set_ylabel('PC2 Loading')
axes[1, 1].set_title('Feature Contributions to Principal Components', fontweight='bold')
axes[1, 1].grid(True, alpha=0.3)
axes[1, 1].set_xlim(-0.8, 0.8)
axes[1, 1].set_ylim(-0.8, 0.8)

plt.suptitle('Figure 2: Cluster Visualizations with PCA', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('figures/pca_cluster_visualizations.png', dpi=300, bbox_inches='tight')
plt.close()
print("✅ Figure saved: figures/pca_cluster_visualizations.png")

# ── Separation Quality Interpretation ──
print("\n📊 PCA Separation Quality Analysis:")
print("-" * 40)
print(f"Total variance explained by first 2 PCs: {sum(pca.explained_variance_ratio_)*100:.2f}%")

if sum(pca.explained_variance_ratio_) > 0.6:
    print("✅ Good separation: First 2 PCs explain > 60% of variance")
else:
    print("⚠️ Moderate separation: First 2 PCs explain < 60% of variance")

# Feature importance in PCA
loadings = pca.components_.T
feature_names = numeric_cols

print("\n🔍 Feature contributions to PC1:")
for feature, load in sorted(zip(feature_names, loadings[:, 0]), key=lambda x: abs(x[1]), reverse=True):
    print(f"   {feature}: {load:.3f}")

print("\n🔍 Feature contributions to PC2:")
for feature, load in sorted(zip(feature_names, loadings[:, 1]), key=lambda x: abs(x[1]), reverse=True):
    print(f"   {feature}: {load:.3f}")

# ── Interpretation of separation quality ──
print("\n📊 Interpretation:")
print("-" * 40)

# Identify dominant features for each PC
pc1_dominant = feature_names[np.argmax(np.abs(loadings[:, 0]))]
pc2_dominant = feature_names[np.argmax(np.abs(loadings[:, 1]))]

print(f"PC1 is dominated by: {pc1_dominant}")
print(f"PC2 is dominated by: {pc2_dominant}")

if abs(loadings[np.argmax(np.abs(loadings[:, 0])), 0]) > 0.7:
    print("✅ Strong separation: Clear dominant features identify workload types")
else:
    print("⚠️ Moderate separation: Multiple features contribute to each PC")

# ============================================================
# 6. CLUSTER COMPARISON & EVALUATION
# ============================================================

print("\n" + "=" * 60)
print("📊 CLUSTER EVALUATION COMPARISON")
print("=" * 60)

# ── Create comparison DataFrame ──
comparison_data = {
    'Algorithm': [],
    'Silhouette Score': [],
    'Davies-Bouldin Index': [],
    'Calinski-Harabasz Score': []
}

for name, results in clustering_results.items():
    if name != 'DBSCAN' or 'n_clusters' in results:
        comparison_data['Algorithm'].append(name)
        comparison_data['Silhouette Score'].append(results['silhouette'])
        comparison_data['Davies-Bouldin Index'].append(results['davies_bouldin'])
        comparison_data['Calinski-Harabasz Score'].append(results['calinski_harabasz'])

comparison_df = pd.DataFrame(comparison_data)
print("\n📋 Algorithm Comparison:")
print(comparison_df.to_string(index=False))

# ── Determine best algorithm ──
best_algo = comparison_df.loc[comparison_df['Silhouette Score'].idxmax(), 'Algorithm']
best_silhouette = comparison_df['Silhouette Score'].max()

print(f"\n🏆 Best Algorithm: {best_algo} (Silhouette Score: {best_silhouette:.4f})")

# ── Plot comparison ──
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Silhouette Score
axes[0].bar(comparison_df['Algorithm'], comparison_df['Silhouette Score'],
            color=['#1f77b4', '#ff7f0e', '#2ca02c'])
axes[0].set_title('Silhouette Score (higher is better)', fontweight='bold')
axes[0].set_ylabel('Score')
axes[0].axhline(y=0.5, color='red', linestyle='--', label='Good threshold (0.5)')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Davies-Bouldin Index
axes[1].bar(comparison_df['Algorithm'], comparison_df['Davies-Bouldin Index'],
            color=['#1f77b4', '#ff7f0e', '#2ca02c'])
axes[1].set_title('Davies-Bouldin Index (lower is better)', fontweight='bold')
axes[1].set_ylabel('Index')
axes[1].grid(True, alpha=0.3)

# Calinski-Harabasz Score
axes[2].bar(comparison_df['Algorithm'], comparison_df['Calinski-Harabasz Score'],
            color=['#1f77b4', '#ff7f0e', '#2ca02c'])
axes[2].set_title('Calinski-Harabasz Score (higher is better)', fontweight='bold')
axes[2].set_ylabel('Score')
axes[2].grid(True, alpha=0.3)

plt.suptitle('Figure 3: Clustering Algorithm Performance Comparison', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('figures/cluster_algorithm_comparison.png', dpi=300, bbox_inches='tight')
plt.close()
print("✅ Figure saved: figures/cluster_algorithm_comparison.png")

# ── Save comparison to CSV ──
comparison_df.to_csv('results/cluster_comparison.csv', index=False)
print("✅ Comparison saved to: results/cluster_comparison.csv")

# ============================================================
# 7. MASTER JSON REPORT
# ============================================================

def generate_master_report_outcome3(kmeans_labels, agg_labels, dbscan_labels=None):
    """Generate master JSON report for Outcome 3."""

    # ── Convert numpy types to native Python types ──
    def convert_to_native(obj):
        if isinstance(obj, np.bool_):
            return bool(obj)
        elif isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return obj

    # ── Stage 3: Clustering ──
    stage3 = {
        "stage": 3,
        "name": "Unsupervised Clustering & Dimensionality Reduction",
        "optimal_k": optimal_k,
        "algorithms": {},
        "best_algorithm": best_algo,
        "best_silhouette": float(best_silhouette),
        "pca": {
            "explained_variance_ratio": pca.explained_variance_ratio_.tolist(),
            "total_explained_variance": float(sum(pca.explained_variance_ratio_)),
            "feature_contributions": dict(zip(numeric_cols, loadings.tolist()))
        }
    }

    for name, results in clustering_results.items():
        if name != 'DBSCAN' or 'n_clusters' in results:
            stage3["algorithms"][name] = {
                "silhouette_score": float(results['silhouette']),
                "davies_bouldin_index": float(results['davies_bouldin']),
                "calinski_harabasz_score": float(results['calinski_harabasz'])
            }
            if name == 'DBSCAN':
                stage3["algorithms"][name]["n_clusters"] = int(results.get('n_clusters', 0))
                stage3["algorithms"][name]["n_noise"] = int(results.get('n_noise', 0))

    # ── Master Report with Student Info ──
    master_report = {
        "student": {
            "registration_number": STUDENT_REG_NO,
            "name": STUDENT_NAME,
            "submission_date": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")
        },
        "project": "ML Cloud Optimisation Lab",
        "outcome": 3,
        "title": "Unsupervised Clustering & Dimensionality Reduction",
        "timestamp": pd.Timestamp.now().isoformat(),
        "seed": SEED,
        "stages": {
            "stage3": stage3
        },
        "leaderboard": {
            "best_silhouette": float(best_silhouette),
            "best_algorithm": best_algo,
            "optimal_k": optimal_k
        },
        "evidence_checklist": {
            "elbow_method_used": True,
            "silhouette_sweep_used": True,
            "kmeans_applied": True,
            "agglomerative_applied": True,
            "dbscan_applied": "DBSCAN" in clustering_results,
            "silhouette_score_computed": True,
            "davies_bouldin_computed": True,
            "calinski_harabasz_computed": True,
            "pca_applied": True,
            "cluster_visualizations_created": True
        }
    }

    # ── Save JSON ──
    with open('results/master_report_outcome3.json', 'w') as f:
        json.dump(master_report, f, indent=2, default=convert_to_native)

    print("\n✅ Master JSON Report saved to: results/master_report_outcome3.json")

    return master_report

# ============================================================
# 8. MAIN EXECUTION
# ============================================================

# ── Generate master report ──
master_report = generate_master_report_outcome3(kmeans_labels, agg_labels, dbscan_labels)

print("\n" + "=" * 60)
print("🎉 OUTCOME 3 COMPLETED SUCCESSFULLY!")
print("=" * 60)
print("\n📋 Results Summary:")
print(f"  Student: {STUDENT_REG_NO}")
print(f"  Name: {STUDENT_NAME}")
print(f"  Optimal K: {optimal_k}")
print(f"  Best Algorithm: {best_algo}")
print(f"  Best Silhouette Score: {best_silhouette:.4f}")
print(f"  PCA Explained Variance: {sum(pca.explained_variance_ratio_)*100:.2f}%")
print("=" * 60)

print("\n📁 Files Created:")
print("  📊 results/clustering_data_scaled.csv")
print("  📊 results/cluster_comparison.csv")
print("  📊 results/master_report_outcome3.json")
print("  📈 figures/optimal_k_selection.png")
print("  📈 figures/pca_cluster_visualizations.png")
print("  📈 figures/cluster_algorithm_comparison.png")