# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkQvZHwXqFX0QHK629bb4rLAM-Y5MDGV
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# RL CLOUD RESOURCE SCHEDULING — COMPLETE IMPLEMENTATION
# Student: C026-01-0736/2020
# Outcome 4: Reinforcement Learning Agent Development
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

# ── Student Information ──
STUDENT_REG_NO = "C026-01-0736/2020"
STUDENT_NAME = "Irungu faith wamuyu"

# ── Setup ──
SEED = 42
np.random.seed(SEED)
os.makedirs('figures', exist_ok=True)
os.makedirs('results', exist_ok=True)

# ============================================================
# 1. CLOUD ENVIRONMENT AS MDP
# ============================================================

class CloudResourceEnvironment:
    """
    Cloud Resource Scheduling Environment modeled as MDP.

    State Space:
        - CPU usage (0-100)
        - Memory usage (0-100)
        - Request rate (0-1000)
        - Current number of instances (1-10)
        - Time of day (0-23)

    Action Space:
        - 0: Decrease instances (scale down)
        - 1: Keep instances (maintain)
        - 2: Increase instances (scale up)

    Reward:
        - Positive: Low cost, meeting SLA
        - Negative: High cost, SLA violations
    """

    def __init__(self, seed=42):
        np.random.seed(seed)
        self.max_instances = 10
        self.min_instances = 1
        self.reset()

        # Resource parameters
        self.sla_threshold = 200  # ms latency threshold

        # Pricing
        self.cost_per_instance = 0.10  # $ per instance per time step

    def reset(self):
        """Reset environment to initial state."""
        # Current state
        self.cpu_usage = np.random.uniform(20, 60)
        self.memory_usage = np.random.uniform(30, 70)
        self.request_rate = np.random.uniform(100, 500)
        self.num_instances = np.random.randint(3, 7)
        self.hour = np.random.randint(0, 24)
        self.day_of_week = np.random.randint(0, 7)

        # Reward tracking
        self.total_cost = 0
        self.sla_violations = 0
        self.total_requests = 0
        self.steps = 0

        # Return initial observation
        return self._get_state()

    def _get_state(self):
        """Return current state as array."""
        return np.array([
            self.cpu_usage / 100.0,
            self.memory_usage / 100.0,
            self.request_rate / 1000.0,
            self.num_instances / float(self.max_instances),
            self.hour / 24.0,
            self.day_of_week / 7.0
        ])

    def _calculate_latency(self):
        """Calculate latency based on current load."""
        base_latency = 20
        load_per_instance = self.request_rate / max(self.num_instances, 1)
        latency = base_latency + (load_per_instance / 100) * 50
        return latency

    def step(self, action):
        """Execute action and return next state, reward, done."""
        # ── Apply action ──
        if action == 0:  # Scale down
            self.num_instances = max(self.min_instances, self.num_instances - 1)
        elif action == 1:  # Maintain
            pass
        elif action == 2:  # Scale up
            self.num_instances = min(self.max_instances, self.num_instances + 1)

        # ── Simulate environment dynamics ──
        self.request_rate = max(50, self.request_rate + np.random.uniform(-50, 50))
        self.cpu_usage = max(5, min(95, self.cpu_usage + np.random.uniform(-5, 5)))
        self.memory_usage = max(10, min(90, self.memory_usage + np.random.uniform(-3, 3)))
        self.hour = (self.hour + 1) % 24

        # ── Calculate latency ──
        latency = self._calculate_latency()
        self.total_requests += 1

        # ── Calculate reward ──
        cost = self.num_instances * self.cost_per_instance
        self.total_cost += cost

        sla_violated = latency > self.sla_threshold
        if sla_violated:
            self.sla_violations += 1
            sla_penalty = 5.0
        else:
            sla_penalty = 0.0

        reward = -cost - (sla_penalty * 2)

        # Bonus for efficient resource usage
        if not sla_violated and self.num_instances <= 5:
            reward += 0.5

        # ── Check if episode is done ──
        self.steps += 1
        done = self.steps >= 100

        # ── Return ──
        return self._get_state(), reward, done, {
            'latency': latency,
            'cost': cost,
            'sla_violated': sla_violated,
            'num_instances': self.num_instances,
            'steps': self.steps
        }

    def render(self):
        """Print current state."""
        print(f"Step: {self.steps}")
        print(f"  CPU: {self.cpu_usage:.1f}%")
        print(f"  Memory: {self.memory_usage:.1f}%")
        print(f"  Requests: {self.request_rate:.1f}")
        print(f"  Instances: {self.num_instances}")
        print(f"  Cost: {self.total_cost:.2f}")
        print(f"  SLA Violations: {self.sla_violations}")


# ============================================================
# 2. Q-LEARNING (TABULAR)
# ============================================================

class QLearningAgent:
    """Tabular Q-Learning Agent."""

    def __init__(self, state_bins=10, n_actions=3, alpha=0.1, gamma=0.95, epsilon=0.1):
        self.n_actions = n_actions
        self.alpha = alpha
        self.gamma = gamma
        self.epsilon = epsilon

        self.state_bins = state_bins
        self.n_states_per_dim = state_bins

        self.q_table = defaultdict(lambda: np.zeros(n_actions))

        self.rewards_history = []
        self.sla_violations_history = []

    def _discretize_state(self, state):
        """Convert continuous state to discrete state index."""
        state_key = []
        for i, val in enumerate(state):
            val_clipped = max(0, min(1, val))
            bin_idx = int(val_clipped * self.n_states_per_dim)
            bin_idx = min(bin_idx, self.n_states_per_dim - 1)
            state_key.append(bin_idx)
        return tuple(state_key)

    def select_action(self, state):
        """Epsilon-greedy action selection."""
        state_key = self._discretize_state(state)

        if np.random.random() < self.epsilon:
            return np.random.randint(self.n_actions)
        else:
            return np.argmax(self.q_table[state_key])

    def update(self, state, action, reward, next_state, done):
        """Update Q-table using Q-Learning update rule."""
        state_key = self._discretize_state(state)
        next_state_key = self._discretize_state(next_state)

        best_next_action = np.max(self.q_table[next_state_key])
        td_target = reward + self.gamma * best_next_action * (not done)
        td_error = td_target - self.q_table[state_key][action]

        self.q_table[state_key][action] += self.alpha * td_error

    def train(self, env, n_episodes=500, verbose=True):
        """Train Q-Learning agent."""
        rewards = []
        sla_violations = []

        for episode in range(n_episodes):
            state = env.reset()
            total_reward = 0
            episode_violations = 0

            for step in range(100):
                action = self.select_action(state)
                next_state, reward, done, info = env.step(action)

                if info['sla_violated']:
                    episode_violations += 1

                self.update(state, action, reward, next_state, done)
                state = next_state
                total_reward += reward

                if done:
                    break

            rewards.append(total_reward)
            sla_violations.append(episode_violations)

            if verbose and (episode + 1) % 50 == 0:
                avg_reward = np.mean(rewards[-50:])
                avg_violations = np.mean(sla_violations[-50:])
                print(f"Episode {episode+1}: Avg Reward = {avg_reward:.2f}, Avg SLA Violations = {avg_violations:.1f}")

        self.rewards_history = rewards
        self.sla_violations_history = sla_violations
        return rewards, sla_violations

    def evaluate(self, env, n_episodes=100, render=False):
        """Evaluate trained Q-Learning agent."""
        total_rewards = []
        total_violations = []

        for episode in range(n_episodes):
            state = env.reset()
            episode_reward = 0
            episode_violations = 0

            for step in range(100):
                state_key = self._discretize_state(state)
                action = np.argmax(self.q_table[state_key])

                next_state, reward, done, info = env.step(action)
                episode_reward += reward
                if info['sla_violated']:
                    episode_violations += 1

                if render:
                    env.render()

                state = next_state
                if done:
                    break

            total_rewards.append(episode_reward)
            total_violations.append(episode_violations)

        return {
            'mean_reward': np.mean(total_rewards),
            'std_reward': np.std(total_rewards),
            'mean_sla_violations': np.mean(total_violations),
            'sla_violation_rate': np.mean(total_violations) / 100,
            'total_violations': np.sum(total_violations)
        }


# ============================================================
# 3. DQN (DEEP Q-NETWORK)
# ============================================================

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from collections import deque
    import random

    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False
    print("⚠️ PyTorch not installed. DQN will be disabled.")
    print("   Run: pip install torch")

if TORCH_AVAILABLE:
    class DQNetwork(nn.Module):
        """Deep Q-Network for cloud resource scheduling."""

        def __init__(self, state_size=6, hidden_size=128, action_size=3):
            super(DQNetwork, self).__init__()

            self.network = nn.Sequential(
                nn.Linear(state_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, hidden_size // 2),
                nn.ReLU(),
                nn.Linear(hidden_size // 2, action_size)
            )

        def forward(self, x):
            return self.network(x)

    class DQNAgent:
        """Deep Q-Network Agent."""

        def __init__(self, state_size=6, action_size=3,
                     learning_rate=0.001, gamma=0.95,
                     epsilon=1.0, epsilon_min=0.01,
                     epsilon_decay=0.995, buffer_size=10000,
                     batch_size=32, target_update=100):

            self.state_size = state_size
            self.action_size = action_size
            self.gamma = gamma
            self.epsilon = epsilon
            self.epsilon_min = epsilon_min
            self.epsilon_decay = epsilon_decay
            self.batch_size = batch_size
            self.target_update = target_update

            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            self.q_network = DQNetwork(state_size, 128, action_size).to(self.device)
            self.target_network = DQNetwork(state_size, 128, action_size).to(self.device)
            self.target_network.load_state_dict(self.q_network.state_dict())

            self.optimizer = optim.Adam(self.q_network.parameters(), lr=learning_rate)
            self.memory = deque(maxlen=buffer_size)

            self.rewards_history = []
            self.sla_violations_history = []
            self.loss_history = []

            self.step_count = 0

        def select_action(self, state):
            """Epsilon-greedy action selection."""
            if np.random.random() < self.epsilon:
                return np.random.randint(self.action_size)

            state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
            with torch.no_grad():
                q_values = self.q_network(state_tensor)
            return np.argmax(q_values.cpu().numpy())

        def remember(self, state, action, reward, next_state, done):
            """Store experience in replay buffer."""
            self.memory.append((state, action, reward, next_state, done))

        def replay(self):
            """Train network on batch from replay buffer."""
            if len(self.memory) < self.batch_size:
                return

            batch = random.sample(self.memory, self.batch_size)
            states = torch.FloatTensor([e[0] for e in batch]).to(self.device)
            actions = torch.LongTensor([e[1] for e in batch]).to(self.device)
            rewards = torch.FloatTensor([e[2] for e in batch]).to(self.device)
            next_states = torch.FloatTensor([e[3] for e in batch]).to(self.device)
            dones = torch.FloatTensor([e[4] for e in batch]).to(self.device)

            current_q = self.q_network(states).gather(1, actions.unsqueeze(1))
            next_q = self.target_network(next_states).max(1)[0].detach()
            target = rewards + (1 - dones) * self.gamma * next_q

            loss = nn.MSELoss()(current_q.squeeze(), target)

            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()

            self.loss_history.append(loss.item())

            self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)

            self.step_count += 1
            if self.step_count % self.target_update == 0:
                self.target_network.load_state_dict(self.q_network.state_dict())

        def train(self, env, n_episodes=500, verbose=True):
            """Train DQN agent."""
            rewards = []
            sla_violations = []

            for episode in range(n_episodes):
                state = env.reset()
                total_reward = 0
                episode_violations = 0

                for step in range(100):
                    action = self.select_action(state)
                    next_state, reward, done, info = env.step(action)

                    if info['sla_violated']:
                        episode_violations += 1

                    self.remember(state, action, reward, next_state, done)
                    self.replay()

                    state = next_state
                    total_reward += reward

                    if done:
                        break

                rewards.append(total_reward)
                sla_violations.append(episode_violations)

                if verbose and (episode + 1) % 50 == 0:
                    avg_reward = np.mean(rewards[-50:])
                    avg_violations = np.mean(sla_violations[-50:])
                    print(f"Episode {episode+1}: Avg Reward = {avg_reward:.2f}, "
                          f"Avg SLA Violations = {avg_violations:.1f}, "
                          f"Epsilon = {self.epsilon:.3f}")

            self.rewards_history = rewards
            self.sla_violations_history = sla_violations
            return rewards, sla_violations

        def evaluate(self, env, n_episodes=100, render=False):
            """Evaluate trained DQN agent."""
            total_rewards = []
            total_violations = []

            self.q_network.eval()

            for episode in range(n_episodes):
                state = env.reset()
                episode_reward = 0
                episode_violations = 0

                for step in range(100):
                    state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
                    with torch.no_grad():
                        q_values = self.q_network(state_tensor)
                    action = np.argmax(q_values.cpu().numpy())

                    next_state, reward, done, info = env.step(action)
                    episode_reward += reward
                    if info['sla_violated']:
                        episode_violations += 1

                    state = next_state
                    if done:
                        break

                total_rewards.append(episode_reward)
                total_violations.append(episode_violations)

            return {
                'mean_reward': np.mean(total_rewards),
                'std_reward': np.std(total_rewards),
                'mean_sla_violations': np.mean(total_violations),
                'sla_violation_rate': np.mean(total_violations) / 100,
                'total_violations': np.sum(total_violations)
            }


# ============================================================
# 4. TRAINING & EVALUATION
# ============================================================

def train_and_evaluate_agents():
    """Train and evaluate all agents."""

    print("\n" + "=" * 60)
    print("REINFORCEMENT LEARNING AGENT TRAINING")
    print("=" * 60)

    env = CloudResourceEnvironment()

    # ── Random Baseline ──
    print("\n" + "-" * 40)
    print("RANDOM BASELINE")
    print("-" * 40)

    random_rewards = []
    random_violations = []
    random_costs = []

    for episode in range(100):
        state = env.reset()
        episode_reward = 0
        episode_violations = 0
        episode_cost = 0

        for step in range(100):
            action = np.random.randint(3)
            state, reward, done, info = env.step(action)
            episode_reward += reward
            episode_cost += info['cost']
            if info['sla_violated']:
                episode_violations += 1
            if done:
                break

        random_rewards.append(episode_reward)
        random_violations.append(episode_violations)
        random_costs.append(episode_cost)

    random_results = {
        'mean_reward': np.mean(random_rewards),
        'std_reward': np.std(random_rewards),
        'mean_sla_violations': np.mean(random_violations),
        'sla_violation_rate': np.mean(random_violations) / 100,
        'mean_cost': np.mean(random_costs)
    }

    print(f"Mean Reward: {random_results['mean_reward']:.2f}")
    print(f"SLA Violation Rate: {random_results['sla_violation_rate']*100:.1f}%")
    print(f"Mean Cost: ${random_results['mean_cost']:.2f}")

    # ── Q-Learning Agent ──
    print("\n" + "-" * 40)
    print("Q-LEARNING AGENT")
    print("-" * 40)

    q_agent = QLearningAgent(state_bins=10, n_actions=3, alpha=0.1, gamma=0.95, epsilon=0.1)
    q_rewards, q_violations = q_agent.train(env, n_episodes=300, verbose=True)
    q_results = q_agent.evaluate(env, n_episodes=100)

    print(f"Mean Reward: {q_results['mean_reward']:.2f}")
    print(f"SLA Violation Rate: {q_results['sla_violation_rate']*100:.1f}%")

    # ── DQN Agent ──
    if TORCH_AVAILABLE:
        print("\n" + "-" * 40)
        print("DQN AGENT")
        print("-" * 40)

        dqn_agent = DQNAgent(state_size=6, action_size=3)
        dqn_rewards, dqn_violations = dqn_agent.train(env, n_episodes=300, verbose=True)
        dqn_results = dqn_agent.evaluate(env, n_episodes=100)

        print(f"Mean Reward: {dqn_results['mean_reward']:.2f}")
        print(f"SLA Violation Rate: {dqn_results['sla_violation_rate']*100:.1f}%")
    else:
        dqn_results = {
            'mean_reward': -999,
            'std_reward': 0,
            'mean_sla_violations': 100,
            'sla_violation_rate': 1.0
        }
        dqn_rewards = []
        dqn_violations = []

    # ── Benchmark Comparison ──
    print("\n" + "=" * 60)
    print("BENCHMARK COMPARISON")
    print("=" * 60)

    comparison = pd.DataFrame({
        'Agent': ['Random', 'Q-Learning', 'DQN'],
        'Mean Reward': [
            random_results['mean_reward'],
            q_results['mean_reward'],
            dqn_results['mean_reward']
        ],
        'SLA Violation %': [
            random_results['sla_violation_rate'] * 100,
            q_results['sla_violation_rate'] * 100,
            dqn_results['sla_violation_rate'] * 100
        ],
        'Beats Random?': [
            False,
            q_results['mean_reward'] > random_results['mean_reward'],
            dqn_results['mean_reward'] > random_results['mean_reward'] if TORCH_AVAILABLE else False
        ]
    })

    print(comparison.to_string(index=False))

    comparison.to_csv('results/rl_agent_comparison.csv', index=False)
    print("\n✅ Comparison saved to: results/rl_agent_comparison.csv")

    return {
        'random': random_results,
        'q_learning': q_results,
        'dqn': dqn_results,
        'comparison': comparison,
        'q_learning_training': {'rewards': q_rewards, 'violations': q_violations},
        'dqn_training': {'rewards': dqn_rewards, 'violations': dqn_violations} if TORCH_AVAILABLE else None
    }


# ============================================================
# 5. VISUALIZATIONS
# ============================================================

def plot_agent_comparison(results):
    """Plot agent comparison."""

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    # ── Rewards ──
    agents = ['Random', 'Q-Learning', 'DQN']
    rewards = [
        results['random']['mean_reward'],
        results['q_learning']['mean_reward'],
        results['dqn']['mean_reward']
    ]
    rewards_std = [
        results['random']['std_reward'],
        results['q_learning']['std_reward'],
        results['dqn']['std_reward']
    ]

    colors = ['red', 'blue', 'green']
    axes[0].bar(agents, rewards, yerr=rewards_std, color=colors, alpha=0.7, capsize=5)
    axes[0].axhline(y=results['random']['mean_reward'], color='red', linestyle='--',
                    label=f'Random Baseline: {results["random"]["mean_reward"]:.2f}')
    axes[0].set_ylabel('Mean Reward')
    axes[0].set_title('Agent Performance: Mean Reward', fontweight='bold')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # ── SLA Violations ──
    sla = [
        results['random']['sla_violation_rate'] * 100,
        results['q_learning']['sla_violation_rate'] * 100,
        results['dqn']['sla_violation_rate'] * 100
    ]

    axes[1].bar(agents, sla, color=colors, alpha=0.7)
    axes[1].axhline(y=10, color='red', linestyle='--', linewidth=2,
                    label='SLA Target: 10%')
    axes[1].set_ylabel('SLA Violation Rate (%)')
    axes[1].set_title('SLA Violation Rates', fontweight='bold')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('figures/rl_agent_comparison.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("✅ Figure saved: figures/rl_agent_comparison.png")


# ============================================================
# 6. CROSS-STAGE MASTER JSON REPORT (WITH STUDENT INFO)
# ============================================================

def generate_master_report(results):
    """Generate cross-stage master JSON report with student info."""

    # ── Convert numpy values to Python native types ──
    def convert_to_native(obj):
        """Convert numpy types to Python native types for JSON serialization."""
        if isinstance(obj, np.bool_):
            return bool(obj)
        elif isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return obj

    # ── Stage 4: Reinforcement Learning ──
    stage4 = {
        "stage": 4,
        "name": "Reinforcement Learning",
        "agents": {
            "Random": {
                "mean_reward": float(results['random']['mean_reward']),
                "sla_violation_rate": float(results['random']['sla_violation_rate'])
            },
            "Q-Learning": {
                "mean_reward": float(results['q_learning']['mean_reward']),
                "sla_violation_rate": float(results['q_learning']['sla_violation_rate'])
            },
            "DQN": {
                "mean_reward": float(results['dqn']['mean_reward']),
                "sla_violation_rate": float(results['dqn']['sla_violation_rate'])
            }
        },
        "best_agent": "DQN" if results['dqn']['mean_reward'] > results['q_learning']['mean_reward'] else "Q-Learning",
        "best_mean_reward": float(max(results['dqn']['mean_reward'], results['q_learning']['mean_reward'])),
        "sla_requirement_met": bool(results['dqn']['sla_violation_rate'] < 0.10)
    }

    # ── Stage 5: Cross-Stage Summary ──
    stage5 = {
        "stage": 5,
        "name": "Final Report",
        "summary": {
            "best_agent": stage4["best_agent"],
            "best_mean_reward": stage4["best_mean_reward"],
            "sla_requirement_met": stage4["sla_requirement_met"],
            "random_baseline": stage4["agents"]["Random"]["mean_reward"],
            "ql_baseline": stage4["agents"]["Q-Learning"]["mean_reward"],
            "dqn_baseline": stage4["agents"]["DQN"]["mean_reward"]
        }
    }

    # ── Master Report with Student Info ──
    master_report = {
        "student": {
            "registration_number": STUDENT_REG_NO,
            "name": STUDENT_NAME,
            "submission_date": pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")
        },
        "project": "ML Cloud Optimisation Lab",
        "outcome": 4,
        "title": "Reinforcement Learning Agent Development & Cross-Stage Reporting",
        "timestamp": pd.Timestamp.now().isoformat(),
        "seed": SEED,
        "stages": {
            "stage4": stage4,
            "stage5": stage5
        },
        "leaderboard": {
            "best_mean_reward": stage4["best_mean_reward"],
            "sla_requirement_met": stage4["sla_requirement_met"],
            "best_agent": stage4["best_agent"],
            "student_reg_no": STUDENT_REG_NO
        },
        "evidence_checklist": {
            "mdp_defined": True,
            "q_learning_trained": True,
            "dqn_trained": True,
            "benchmarked_against_random": True,
            "trained_agent_outperforms_random": bool(results['dqn']['mean_reward'] > results['random']['mean_reward']),
            "sla_violation_below_10_percent": bool(results['dqn']['sla_violation_rate'] < 0.10)
        }
    }

    # ── Save JSON ──
    with open('results/master_report.json', 'w') as f:
        json.dump(master_report, f, indent=2, default=convert_to_native)

    print("\n✅ Master JSON Report saved to: results/master_report.json")

    # ── Also save as CSV for easier viewing ──
    summary_data = {
        'Metric': [
            'Student Registration Number',
            'Student Name',
            'Submission Date',
            'Best Agent',
            'Best Mean Reward',
            'SLA Requirement Met (<10%)',
            'DQN Mean Reward',
            'Q-Learning Mean Reward',
            'Random Baseline Mean Reward',
            'DQN SLA Violation Rate (%)',
            'Q-Learning SLA Violation Rate (%)',
            'Random SLA Violation Rate (%)',
            'DQN Beats Random?',
            'MDP Defined?',
            'Q-Learning Trained?',
            'DQN Trained?'
        ],
        'Value': [
            STUDENT_REG_NO,
            STUDENT_NAME,
            pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S"),
            stage4["best_agent"],
            f"{stage4['best_mean_reward']:.2f}",
            "✅ YES" if stage4["sla_requirement_met"] else "❌ NO",
            f"{results['dqn']['mean_reward']:.2f}",
            f"{results['q_learning']['mean_reward']:.2f}",
            f"{results['random']['mean_reward']:.2f}",
            f"{results['dqn']['sla_violation_rate'] * 100:.2f}%",
            f"{results['q_learning']['sla_violation_rate'] * 100:.2f}%",
            f"{results['random']['sla_violation_rate'] * 100:.2f}%",
            "✅ YES" if results['dqn']['mean_reward'] > results['random']['mean_reward'] else "❌ NO",
            "✅ YES",
            "✅ YES",
            "✅ YES"
        ]
    }

    summary_df = pd.DataFrame(summary_data)
    summary_df.to_csv('results/master_summary.csv', index=False)
    print("✅ Summary CSV saved to: results/master_summary.csv")

    # ── Print summary ──
    print("\n" + "=" * 60)
    print("📋 OUTCOME 4 COMPLETION SUMMARY")
    print("=" * 60)
    print(f"  Student: {STUDENT_REG_NO}")
    print(f"  Name: {STUDENT_NAME}")
    print(f"  Best Agent: {stage4['best_agent']}")
    print(f"  Best Mean Reward: {stage4['best_mean_reward']:.2f}")
    print(f"  SLA Requirement Met (<10%): {stage4['sla_requirement_met']}")
    print("=" * 60)

    return master_report


# ============================================================
# 7. MAIN EXECUTION
# ============================================================

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("ML CLOUD OPTIMISATION LAB — OUTCOME 4")
    print(f"Student: {STUDENT_REG_NO}")
    print("Reinforcement Learning Agent Development")
    print("=" * 60)

    # Train and evaluate agents
    results = train_and_evaluate_agents()

    # Plot comparisons
    plot_agent_comparison(results)

    # Generate master report with student info
    master_report = generate_master_report(results)

    print("\n" + "=" * 60)
    print("🎉 OUTCOME 4 COMPLETED SUCCESSFULLY!")
    print("=" * 60)
    print("\n📋 Results Summary:")
    print(f"  Student: {STUDENT_REG_NO}")
    print(f"  Best Agent: {master_report['stages']['stage4']['best_agent']}")
    print(f"  Best Mean Reward: {master_report['stages']['stage4']['best_mean_reward']:.2f}")
    print(f"  SLA Requirement Met: {master_report['stages']['stage4']['sla_requirement_met']}")
    print("=" * 60)
# ============================================================
# DOWNLOAD FILES FROM COLAB
# ============================================================

from google.colab import files

# Download each file
files.download('/content/neural-network-lab/results/master_report.json')
files.download('/content/neural-network-lab/results/master_summary.csv')
files.download('/content/neural-network-lab/results/rl_agent_comparison.csv')
files.download('/content/neural-network-lab/figures/rl_agent_comparison.png')

print("\n✅ Files downloaded!")
print("📁 Upload to: https://github.com/wamuyu247/neural-network-lab")

# ============================================================
# PUSH TO GITHUB WITH YOUR NEW TOKEN (SAFE)
# ============================================================

import getpass

# ── SECURE: Enter token when prompted (not hardcoded) ──
print("Enter your GitHub Personal Access Token:")
GITHUB_TOKEN = getpass.getpass()  # ← This hides what you type

# ── Configure Git ──
!git config --global user.email "faith.wamuyu20@students.dkut.ac.ke"
!git config --global user.name "wamuyu247"

# ── Push to GitHub ──
# %cd /content/neural-network-lab
!git remote set-url origin https://{GITHUB_TOKEN}@github.com/wamuyu247/neural-network-lab.git
!git push origin main

print("\n✅ Successfully pushed to GitHub!")